routes/web.php
<?php

use App\Models\AssetFile;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StateController;
use App\Http\Controllers\ComplaintController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\PermohonanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/test/test2', function () {
    echo 'test';
});


// Route::get('/permohonan', function () {

//     return view('permohonan.index');
    
// });

Route::get('/permohonan/index',[PermohonanController::class,'index']);


Route::get('/permohonan/create',[PermohonanController::class,'create'])->name('permohonan.create');

Route::post('/permohonan/store',[PermohonanController::class,'store'])->name('permohonan.store');

Route::get('/permohonan/success/{complainant}',[PermohonanController::class,'success'])->name('permohonan.success');





Route::get('report/view-image/{fileid}', function($fileid){
    $source = AssetFile::find($fileid);
    if($source){
        $file = public_path('/storage/'.$source->location);
    }else{
        $file = public_path('/storage/uploads/report/no_image.jpg');
    }

    return response()->file($file);
})->name('download.file'); 


Route::prefix('admin')->group(function () {

    
    Route::name('admin.')->group(function () {
        
        Route::get('/permohonan/update/{id?}',[PermohonanController::class,'update'])->name('permohonan.update');

        Route::get('/state',[StateController::class,'index'])->name('state.index');

        Route::resource('complaint', ComplaintController::class);

    });



});


Route::resource('customer', CustomerController::class);

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Pagination\LengthAwarePaginator;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        // $curl = curl_init();
        // curl_setopt_array($curl, [
        //     CURLOPT_URL => 'http://amtis.opengw.net:8089/l10api/public/api/v1/customer?'.http_build_query(['page' => request('page') ?? null]),
        //     CURLOPT_RETURNTRANSFER => true,
        //     CURLOPT_CUSTOMREQUEST => 'GET'
        // ]);
        // $response = curl_exec($curl);
        // curl_close($curl);
        // dd($response);
        // $data = json_decode($response, true);
        // dd($data);
        $response = Http::get('http://amtis.opengw.net:8089/l10api/public/api/v1/customer', ['page' => request('page') ?? null]);
        $data = $response->json();
        $paginator = new LengthAwarePaginator(
            collect($data['data']),
            $data['meta']['total'],
            $data['meta']['per_page'],
            $data['meta']['current_page'],
            ['path' => route('customer.index')]
        );
        // dd($data);
        return view('customer.index', compact('paginator'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('customer.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required',
            'email' => 'required',
            'type' => 'required',
            'address' => 'required',
            'state' => 'required',
            'city' => 'required',
        ],[
            'name.required' => 'nama diperlukan'
        ]);
        $response = Http::post('http://amtis.opengw.net:8089/l10api/public/api/v1/customer', $validated);
        if($response->successful()){
            return to_route('customer.index')->withSuccess('Customer Created');
        }
        // dd($response->json());
        return back()->withErrors($response->json()['errors'])
        ->withInput();
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $response = Http::get("http://amtis.opengw.net:8089/l10api/public/api/v1/customer/$id");
        if($response->successful()){
            $customer = $response->json()['data'];
            return view('customer.show', compact('customer'));
        }
        return to_route('customer.index')
        ->withError('Something Wrong!');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $response = Http::get("http://amtis.opengw.net:8089/l10api/public/api/v1/customer/$id");
        if($response->successful()){
            $customer = $response->json()['data'];
            return view('customer.edit', compact('customer'));
        }
        return to_route('customer.index')
        ->withError('Something Wrong!');
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $validated = $request->validate([
            'name' => 'required',
            'email' => 'required',
            'type' => 'required',
            'address' => 'required',
            'state' => 'required',
            'city' => 'required',
        ],[
            'name.required' => 'nama diperlukan'
        ]);
        $response = Http::put("http://amtis.opengw.net:8089/l10api/public/api/v1/customer/$id", $validated);
        if($response->successful()){
            return to_route('customer.index')->withSuccess('Customer Updated');
        }
        dd($response->json());
        return back()->withErrors($response->json()['errors'])
        ->withInput();
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $response = Http::delete("http://amtis.opengw.net:8089/l10api/public/api/v1/customer/$id");
        if($response->successful()){
            return to_route('customer.index')
            ->withSuccess('Customer Deleted!');
        }
        return to_route('customer.index')
        ->withError('Something wrong!');
    }
}

resources/views/customer/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Add Customer</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('customer.store') }}" method="POST">
                            @csrf
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label">Name</label>
                                        <input type="text" id="name" name="name" class="form-control">
                                    </div>
                                    @error('name')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label">Type</label>
                                        <input type="text" id="type" name="type" class="form-control">
                                    </div>
                                    @error('type')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label">Email</label>
                                        <input type="text" id="email" name="email" class="form-control">
                                    </div>
                                    @error('email')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label">Address</label>
                                        <input type="text" id="address" name="address" class="form-control">
                                    </div>
                                    @error('address')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label">City</label>
                                        <input type="text" id="city" name="city" class="form-control">
                                    </div>
                                    @error('city')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label">State</label>
                                        <input type="text" id="state" name="state" class="form-control">
                                    </div>
                                    @error('state')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary btn-submit">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<script>
    $('.btn-submit').on('click', function(e){
        e.preventDefault();
        let formData = {
            name: $('#name').val(),
            email: $('#email').val(),
            type: $('#type').val(),
            address: $('#address').val(),
            state: $('#state').val(),
            city: $('#city').val()
        };
        let request = $.ajax({
            url: "http://amtis.opengw.net:8089/l10api/public/api/v1/customer",
            method: "POST",
            data: formData
        });
        request.done(function(response){
            alert('Customer Created!');
            window.location.href = "{{ route('customer.index') }}";
        });
        request.fail(function(xhr){
            alert(xhr.responseText);
        });
    });
</script>
@endsection

resources/views/customer/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Edit Customer</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('customer.update', $customer['id']) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label">Name</label>
                                        <input type="text" id="name" name="name" value="{{ $customer['name'] }}" class="form-control">
                                    </div>
                                    @error('name')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label">Type</label>
                                        <input type="text" id="type" name="type" value="{{ $customer['type'] }}" class="form-control">
                                    </div>
                                    @error('type')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label">Email</label>
                                        <input type="text" id="email" name="email" value="{{ $customer['email'] }}" class="form-control">
                                    </div>
                                    @error('email')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label">Address</label>
                                        <input type="text" id="address" name="address" value="{{ $customer['address'] }}" class="form-control">
                                    </div>
                                    @error('address')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label">City</label>
                                        <input type="text" id="city" name="city" value="{{ $customer['city'] }}" class="form-control">
                                    </div>
                                    @error('city')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label">State</label>
                                        <input type="text" id="state" name="state" value="{{ $customer['state'] }}" class="form-control">
                                    </div>
                                    @error('state')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary btn-submit">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/customer/index.blade.php
@extends('layouts.app')
@section('content')
    @if ($message = Session::get('success'))
        <div class="alert alert-success text-white fade show">
            <span class="alert-text">{{ $message }}</span>
        </div>
    @elseif($message = Session::get('error'))
        <div class="alert alert-danger text-white fade show">
            <span class="alert-text">{{ $message }}</span>
        </div>
    @endif
    <a class="btn btn-success float-end" 
    href="{{ route('customer.create') }}">Create</a>
    <table class="table">
        <thead>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
            <th>Address</th>
            <th>Action</th>
        </thead>
        <tbody>
            @foreach($paginator as $key => $customer)
            <tr>
                <td>{{ $key + $paginator->firstItem() }}</td>
                <td>{{ $customer['name'] }}</td>
                <td>{{ $customer['email'] }}</td>
                <td>{{ $customer['address'] }}</td>
                <td>
                    <a class="btn btn-info" 
                    href="{{ route('customer.show', $customer['id']) }}">
                        View</a>
                    <a class="btn btn-warning" 
                    href="{{ route('customer.edit', $customer['id']) }}">
                        Edit</a>
                    <form method="POST" 
                    action="{{ route('customer.destroy', $customer['id']) }}">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    {{ $paginator->links() }}
@endsection

resources/views/customer/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4>View Customer</h4>
                    </div>
                    <div class="card-body">
                    
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label">Name</label>
                                        <input type="text" id="name" name="name" value="{{ $customer['name'] }}" class="form-control">
                                    </div>
                                    
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label">Type</label>
                                        <input type="text" id="type" name="type" value="{{ $customer['type'] }}" class="form-control">
                                    </div>
                                    
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label">Email</label>
                                        <input type="text" id="email" name="email" value="{{ $customer['email'] }}" class="form-control">
                                    </div>
                                    
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label">Address</label>
                                        <input type="text" id="address" name="address" value="{{ $customer['address'] }}" class="form-control">
                                    </div>
                                    
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label">City</label>
                                        <input type="text" id="city" name="city" value="{{ $customer['city'] }}" class="form-control">
                                    </div>
                                    
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label">State</label>
                                        <input type="text" id="state" name="state" value="{{ $customer['state'] }}" class="form-control">
                                    </div>
                                    
                                </div>
                            </div>
                            
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </div>
    </div>
@endsection