routes/web.php
<?php

use App\Models\AssetFile;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StateController;
use App\Http\Controllers\ComplaintController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\PermohonanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/test/test2', function () {
    echo 'test';
});


// Route::get('/permohonan', function () {

//     return view('permohonan.index');
    
// });

Route::get('/permohonan/index',[PermohonanController::class,'index']);


Route::get('/permohonan/create',[PermohonanController::class,'create'])->name('permohonan.create');

Route::post('/permohonan/store',[PermohonanController::class,'store'])->name('permohonan.store');

Route::get('/permohonan/success/{complainant}',[PermohonanController::class,'success'])->name('permohonan.success');





Route::get('report/view-image/{fileid}', function($fileid){
    $source = AssetFile::find($fileid);
    if($source){
        $file = public_path('/storage/'.$source->location);
    }else{
        $file = public_path('/storage/uploads/report/no_image.jpg');
    }

    return response()->file($file);
})->name('download.file'); 


Route::prefix('admin')->group(function () {

    
    Route::name('admin.')->group(function () {
        
        Route::get('/permohonan/update/{id?}',[PermohonanController::class,'update'])->name('permohonan.update');

        Route::get('/state',[StateController::class,'index'])->name('state.index');

        Route::resource('complaint', ComplaintController::class);

    });



});


Route::resource('customer', CustomerController::class);

app/Http/Controllers/PermohonanController.php
<?php

namespace App\Http\Controllers;

use App\Models\AssetFile;
use Illuminate\Http\Request;
use App\Helpers\CustomHelpers;
use App\Models\ComplainantDetail;
use App\Mail\ComplaintApplication;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Auth\Events\Validated;

class PermohonanController extends Controller
{


    public function index(){

    $datasearch=request(['complainant_name','complainant_status']);

      $data['modelComp']=  $modelComp =
       ComplainantDetail::with(['statusCom','nationalityAsset'])
       ->latest()
       ->filter($datasearch)
       ->paginate(10);


       $data['statusLookup']=  CustomHelpers::getComplaintStatus();
  
        return view('permohonan.index',$data);
    }



    public function create(){



     return view('permohonan.create');


    }

    public function store(Request $request){


        
  
        // $input=$request->all();
        // $input['complainant_status']='STS001';


        // $complainant=  ComplainantDetail::create($input);
        // $complainant= null;

       $validated= $request->
       validate([
        'complainant_name'=>'required',
        'complainant_title'=>'required',
        'complainant_nationality'=>'required',
        'complainant_identity'=>'required',
        'complainant_complaint'=>'required',
        'file_upload'=>'nullable|max:2048'
         ],['complainant_name.required'=>'Sila masukan nama anda']);


         $validated['complainant_status']='STS001';

   
       $complainant=  ComplainantDetail::create($validated);



    //    save file
       if($complainant->id ){

        if($request->file_upload){

        foreach($request->file_upload as $key=>$file){

            

            $filename="doc_$key".time().'com'.$complainant->id.'.'.$file->getClientOriginalExtension();
          
            // dd($file);
            $filepath=$file->storeAs('uploads/complainant',$filename,'public');

            
            if($file??''){

                $asset=new AssetFile();
                $asset->name=$filename;
                $asset->location=$filepath;
                $asset->ext=$file->getMimeType();
                $asset->category='file_complainant';
                $asset->reference_id=$complainant->id;
                $asset->reference_type='complainant_details';
                $asset->save();
                 

                

            }//if2

            

        }//forecah1

    }
      
            $emailto=$complainant->complainant_email??'recipient@example.com';


           Mail::to($emailto)
           ->cc('sukor@gmail.com')
           ->send(new ComplaintApplication($complainant));

        

            return redirect()->route('permohonan.success',$complainant)->with('success', 'Complainant created successfully.');

       }else{

        return redirect()->route('permohonan.create')->withErrors(['error' => 'Complainant created No successfully.']);

       }

    //    end save file



    }


    public function success(ComplainantDetail $complainant){


        $data['data']=$complainant;

        return view('permohonan.success',$data);



    }

    


    // public function update($id=''){
        

    //     $d['id']=$id;
    //     $d['name']='nama saya ali';
    //     // dd($id);


    //     return view('permohonan.update',$d);
    // }


    public function update($id=''){
        

     
        $name='nama saya ali';
        // dd($id);


        return view('permohonan.update',compact('id','name'));
    }




    
}

resources/views/permohonan/create.blade.php
@extends('layouts.land')

@section('title','create')

@section('content')

@php
    // use App\Helpers\CustomHelpers;
@endphp

{{-- <form  method="POST" enctype="multipart/form-data">
<input type="text" name=''>

</form> --}}


@if ($errors->has('error'))
<div class="alert alert-danger">
    {{ $errors->first('error') }}
</div>
@endif

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Create Complaint</h4>
                </div>
                <div class="card-body">
                    <form  action="{{route('permohonan.store')}}"  method="POST"  enctype="multipart/form-data">
 
                        @csrf


                        <div class="row">
    <div class="col-md-4">
        <div class="input-group input-group-static mb-4">
            <label>Title</label>
            <select class="form-control" name='complainant_title'>
                <option value="">Sila pilih</option>
                @foreach (App\Helpers\CustomHelpers::getTitle() as $item)
                    <option value='{{ $item }}' {{ (old('complainant_title',$data->complainant_title??'')??'') == $item ? 'selected' : '' }}>{{ $item }}</option>
                @endforeach
            </select>
        </div>
        @error('complainant_title')
            <span class="text-danger">{{ $message }}</span>
        @enderror
    </div>
    <div class="col-md-8">
        <div class="input-group input-group-static mb-4">
            <label>Name</label>
            <input type="text" class="form-control" name="complainant_name" value="{{ old('complainant_name',$data->complainant_name??'') }}">
        </div>
        @error('complainant_name')
            <span class="text-danger">{{ $message }}</span>
        @enderror
    </div>
</div>

{{-- input line 2 --}}


<div class="row">
    <div class="col-md-4">
        <div class="input-group input-group-static mb-4">
            <label>Nationality</label>
            <select class="form-control" name='complainant_nationality'>
                <option value="">Sila pilih</option>
                @foreach (App\Helpers\CustomHelpers::getNationality() as $key2=> $item2)
                    <option value='{{ $key2 }}' 
                    {{ (old('complainant_nationality',$data->complainant_nationality??'')??'') == $key2 ? 'selected' : '' }}>{{ $item2 }}</option>
                @endforeach
            </select>
        </div>
        @error('complainant_nationality')
            <span class="text-danger">{{ $message }}</span>
        @enderror
    </div>
    <div class="col-md-8">
        <div class="input-group input-group-static mb-4">
            <label>Mykad/Paspport</label>
            <input type="text" class="form-control" name="complainant_identity" value="{{ old('complainant_identity',$data->complainant_identity??'') }}">
        </div>
        @error('complainant_identity')
            <span class="text-danger">{{ $message }}</span>
        @enderror
    </div>
</div>

{{-- end input line 2 --}}

{{-- input line 3 --}}

<div class="row">

    <div class="col-md-12">
        <div class="input-group input-group-static mb-4">
            <label>Complaint</label>
            <input type="text" class="form-control" name="complainant_complaint" value="{{ old('complainant_complaint',$data->complainant_complaint??'') }}">
        </div>
        @error('complainant_complaint')
            <span class="text-danger">{{ $message }}</span>
        @enderror
    </div>

</div>

{{-- input line 3 --}}


{{-- input line 4 --}}

<div class="row">

    <div class="col-md-12">
        <div class="input-group input-group-static mb-4">
            <label>file 1</label>
            <input type="file" class="form-control" name="file_upload[]" >
        </div>
        @error('file_upload')
            <span class="text-danger">{{ $message }}</span>
        @enderror
    </div>

</div>

<div class="row">

    <div class="col-md-12">
        <div class="input-group input-group-static mb-4">
            <label>file 2</label>
            <input type="file" class="form-control" name="file_upload[]" >
        </div>
        @error('file_upload')
            <span class="text-danger">{{ $message }}</span>
        @enderror
    </div>

</div>

{{-- input line 4 --}}
                    

                        <button type="submit" class="btn btn-primary">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>




@endsection

resources/views/permohonan/index.blade.php
@extends('layouts.app')

@section('title','test 2')

@section('content')
    <p>This is my body content ini test saja.</p>



    <a  class='btn btn-danger' href="{{url('/permohonan/update/2')}}">update guna url</a>

    <a  class='btn btn-info' href="{{route('admin.permohonan.update',['id'=>2])}}">update guna name route</a>

<form >
    <div class="row">
        <div class="col-md-4">

<div class="input-group input-group-outline mb-4">
    <label class="form-label">Nama</label>
    <input name='complainant_name' type="text" class="form-control">
  </div>
</div>
</div>

<div class="row">
    <div class="col-md-4">

<div class="input-group input-group-outline mb-4">
<label class="form-label">Status</label>
<select  class="form-control" name="complainant_status" id="complainant_status" >
@foreach ($statusLookup as $statuskey=>$statusitem)
    <option value="{{$statuskey}}">{{$statusitem}}</option>
@endforeach

</select>

</div>
</div>
</div>



  <button class='btn btn-info' type='submit'>Cari</button>

</form>




<table class='table'>

   @foreach ($modelComp as $item)

   <tr>
    <td>{{$item->complainant_name}}</td>
    <td>{{$item->statusCom->name??''}}</td>
    <td>{{$item->nationalityAsset->name??''}}</td>
   </tr>
        

   
    @endforeach
    
    
</table>

{{ $modelComp->appends(request()->except('page'))->links() }}

@endsection

resources/views/permohonan/success.blade.php
@extends('layouts.land')

@section('title','success')

@section('content')


@if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title"> Complaint</h4>
                </div>
                <div class="card-body">
<div class="row">
    <div class="col-md-4">
        <div class="input-group input-group-static mb-4">
            <label>Title</label>
            <select @disabled(true) class="form-control" name='complainant_title'>
                <option value="">Sila pilih</option>
                @foreach (App\Helpers\CustomHelpers::getTitle() as $item)
                    <option value='{{ $item }}' {{ (old('complainant_title',$data->complainant_title??'')??'') == $item ? 'selected' : '' }}>{{ $item }}</option>
                @endforeach
            </select>
        </div>
        @error('complainant_title')
            <span class="text-danger">{{ $message }}</span>
        @enderror
    </div>
    <div class="col-md-8">
        <div class="input-group input-group-static mb-4">
            <label>Name</label>
            <input @disabled(true) type="text" class="form-control" name="complainant_name" value="{{ old('complainant_name',$data->complainant_name??'') }}">
        </div>
        @error('complainant_name')
            <span class="text-danger">{{ $message }}</span>
        @enderror
    </div>
</div>

{{-- input line 2 --}}


<div class="row">
    <div class="col-md-4">
        <div class="input-group input-group-static mb-4">
            <label>Nationality</label>
            <select @disabled(true) class="form-control" name='complainant_nationality'>
                <option value="">Sila pilih</option>
                @foreach (App\Helpers\CustomHelpers::getNationality() as $key2=> $item2)
                    <option value='{{ $key2 }}' 
                    {{ (old('complainant_nationality',$data->complainant_nationality??'')??'') == $key2 ? 'selected' : '' }}>{{ $item2 }}</option>
                @endforeach
            </select>
        </div>
        @error('complainant_nationality')
            <span class="text-danger">{{ $message }}</span>
        @enderror
    </div>
    <div class="col-md-8">
        <div class="input-group input-group-static mb-4">
            <label>Mykad/Paspport</label>
            <input @disabled(true) type="text" class="form-control" name="complainant_identity" value="{{ old('complainant_identity',$data->complainant_identity??'') }}">
        </div>
        @error('complainant_identity')
            <span class="text-danger">{{ $message }}</span>
        @enderror
    </div>
</div>

{{-- end input line 2 --}}

{{-- input line 3 --}}

<div class="row">

    <div class="col-md-12">
        <div class="input-group input-group-static mb-4">
            <label>Complaint</label>
            <input @disabled(true) type="text" class="form-control" name="complainant_complaint" value="{{ old('complainant_complaint',$data->complainant_complaint??'') }}">
        </div>
        @error('complainant_complaint')
            <span class="text-danger">{{ $message }}</span>
        @enderror
    </div>

</div>

{{-- input line 3 --}}


{{-- input line 4 --}}
@php
$bil=0;
@endphp
@foreach ($data->fileAsset as $fileas)
@php
$bil++;
@endphp

<div class="row">

    <div class="col-md-12">
        <div class="input-group input-group-static mb-4">
     
            <a class='btn btn-info' href="{{route('download.file',['fileid'=>$fileas->id])}}"> Download file {{$bil}}</a>
        </div>
        
    </div>

</div>
    
@endforeach
    

                </div>
            </div>
        </div>
    </div>
</div>



{{-- input line 4 --}}
                    


@endsection

resources/views/permohonan/update.blade.php
@extends('layouts.app')

@section('title','test 2')

@section('content')
    <p>id:{{$id}}</p>
    <p>nama:{{$name}}</p>



@endsection